CREATE DATABASE "LabControl"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE TABLE LABORATORIOS (
LAB_ID SERIAL NOT NULL PRIMARY KEY,
LAB_DESC VARCHAR(50),
LAB_QUANT_COMP INT,
STD_ID INT
);

CREATE TABLE RESERVAS (
RES_ID SERIAL NOT NULL PRIMARY KEY,
RES_DATA DATE,
RES_HR_INI TIME,
RES_HR_FIM TIME,
PES_ID INT,
LAB_ID INT,
STD_ID INT,
FOREIGN KEY(LAB_ID) REFERENCES LABORATORIOS (LAB_ID)
);

CREATE TABLE TIPOS (
TIP_ID SERIAL NOT NULL PRIMARY KEY,
TIP_DESC VARCHAR(100)
);

INSERT INTO TIPOS VALUES(1, 'Auditor');
INSERT INTO TIPOS VALUES(2, 'Gestor');
INSERT INTO TIPOS VALUES(3, 'Tecnico');
INSERT INTO TIPOS VALUES(4, 'Professor');
INSERT INTO TIPOS VALUES(5, 'Aluno');

CREATE TABLE RES_COMP (
RC_ID SERIAL NOT NULL PRIMARY KEY,
RC_DATA DATE,
RC_HR_INI TIME,
RC_HR_FIM TIME,
PES_ID INT,
COM_ID INT,
STD_ID INT
);

CREATE TABLE COMPUTADORES (
COM_ID SERIAL NOT NULL PRIMARY KEY,
COM_DESC VARCHAR(100),
LAB_ID INT,
STD_ID INT,
FOREIGN KEY(LAB_ID) REFERENCES LABORATORIOS (LAB_ID)
);

CREATE TABLE SERVICOS (
SERV_ID SERIAL NOT NULL PRIMARY KEY,
SERV_DESC VARCHAR(100)
);

INSERT INTO SERVICOS VALUES(1, 'Instalação');
INSERT INTO SERVICOS VALUES(2, 'Formatação');
INSERT INTO SERVICOS VALUES(3, 'Manutenção');
INSERT INTO SERVICOS VALUES(4, 'Limpeza');
INSERT INTO SERVICOS VALUES(5, 'Suporte');
INSERT INTO SERVICOS VALUES(6, 'Outros');

CREATE TABLE STATUS (
STD_ID SERIAL NOT NULL PRIMARY KEY,
STA_DESC VARCHAR(50)
);

INSERT INTO STATUS VALUES(1, 'Liberado');
INSERT INTO STATUS VALUES(2, 'Bloqueado');
INSERT INTO STATUS VALUES(3, 'Disponivel');
INSERT INTO STATUS VALUES(4, 'Manutenção');
INSERT INTO STATUS VALUES(5, 'Reservado');
INSERT INTO STATUS VALUES(6, 'Aprovado');
INSERT INTO STATUS VALUES(7, 'Reprovado');
INSERT INTO STATUS VALUES(8, 'Pendente');
INSERT INTO STATUS VALUES(9, 'Executado');

CREATE TABLE PES_SER (
PS_ID SERIAL NOT NULL PRIMARY KEY,
LAB_ID INT,
STD_ID INT,
PES_ID_SOL INT,
PES_ID_EXE INT,
SERV_ID INT,
PS_OBS VARCHAR(100),
PS_DT_INI DATE,
PS_HR_INI TIME,
PS_DT_FIM DATE,
PS_HR_FIM TIME,
FOREIGN KEY(LAB_ID) REFERENCES LABORATORIOS (LAB_ID),
FOREIGN KEY(STD_ID) REFERENCES STATUS (STD_ID),
FOREIGN KEY(SERV_ID) REFERENCES SERVICOS (SERV_ID)
);

CREATE TABLE PESSOAS (
PES_ID SERIAL NOT NULL PRIMARY KEY,
PES_MATRI INT,
PES_NOME VARCHAR(100),
PES_EMAIL VARCHAR(50),
PES_CELULAR VARCHAR(20),
PES_LOGIN VARCHAR(50),
PES_SENHA VARCHAR(50),
TIP_ID INT,
STD_ID INT,
FOREIGN KEY(TIP_ID) REFERENCES TIPOS (TIP_ID),
FOREIGN KEY(STD_ID) REFERENCES STATUS (STD_ID)
);


INSERT INTO PESSOAS VALUES(1, '1', 'Ewerton Maik', 'ewertonmsa@hotmail.com', '9999-9999', 'ewerton', '123', 1, 1);


ALTER TABLE LABORATORIOS ADD FOREIGN KEY(STD_ID) REFERENCES STATUS (STD_ID);
ALTER TABLE RESERVAS ADD FOREIGN KEY(PES_ID) REFERENCES PESSOAS (PES_ID);
ALTER TABLE RESERVAS ADD FOREIGN KEY(STD_ID) REFERENCES STATUS (STD_ID);
ALTER TABLE RES_COMP ADD FOREIGN KEY(PES_ID) REFERENCES PESSOAS (PES_ID);
ALTER TABLE RES_COMP ADD FOREIGN KEY(COM_ID) REFERENCES COMPUTADORES (COM_ID);
ALTER TABLE RES_COMP ADD FOREIGN KEY(STD_ID) REFERENCES STATUS (STD_ID);
ALTER TABLE COMPUTADORES ADD FOREIGN KEY(STD_ID) REFERENCES STATUS (STD_ID);
ALTER TABLE PES_SER ADD FOREIGN KEY(PES_ID_SOL) REFERENCES PESSOAS (PES_ID);
ALTER TABLE PES_SER ADD FOREIGN KEY(PES_ID_EXE) REFERENCES PESSOAS (PES_ID);